apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: pmerta22/dev-ops-web-shavira:latest # ganti dengan nama image Docker Hub yang sesuai
        ports:
        - containerPort: 3000
